version: '3' #docker-version
services:
  www:
    image: php:apache
    volumes:
      - "./:/var/www/html" #sync project to container
    ports:
      - 81:81
      - 80:80 #for future ssl traffic

  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=php_docker #nom de la base de données
      - MYSQL_USER=php_docker #username
      - MYSQL_PASSWORD=password #this should live in a env var   #password
      - MYSQL_ALLOW_EMPTY_PASSWORD=1 #like TRUE pour test
    volumes:
      - ./database:/var/lib/mysql # Montage d'un volume pour stocker les données

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306

volumes:
  database: # Définition du volume pour la base de données
